### ISSUE TITLE
Needs build instructions

### ISSUE THREAD

**Issue by tlhonmey** [gnudles/stereograma#1]
I don't see anything that looks like build-system files, and there's no obvious documentation of the build order.  

Figuring it out by guess and check is a serious hassle.  Can we at least get a list of what order to build the pieces in?  Or preferably a makefile or something that will just handle it?

**Comment by luisvalenzuelar** [comment]
Agree. Have no idea how this is to be used. Please help the newbies like me! There are tons of .ply samples out there to start playing around!

Thanks

**Comment by gnudles** [comment]
Oh, sorry, I thought that it was intuitive. You just need to open the project file with QtCreator.

**Comment by gnudles** [comment]
You might also generate a makefile from the .pro file with qmake simply by running:
qmake stereograma.pro

**Comment by luisvalenzuelar** [comment]
Great. Thanks! (Maybe you can add this simple instructions to the Readme.md file :)

**Comment by gnudles** [comment]
Sure.
